#!/bin/bash
WORK_TREE="/var/www/carlofazioli.com/html"
GIT_DIR="/srv/git/website.git"
while read oldrev newrev ref
do
    if [[ $ref =~ .*/main$ ]];
    then
        echo "Main ref received.  Deploying main branch to production..."
        git --work-tree=$WORK_TREE --git-dir=$GIT_DIR checkout -f main
        echo "    ....done."
        echo "Moving hooks..."
        cp $WORK_TREE/hooks/* $GIT_DIR/hooks/
        echo "    ....done."
    else
        echo "Ref $ref successfully received."
        echo "Doing nothing: only the main branch may be deployed on this server."
    fi
done
