#!/bin/bash
while read oldrev newrev ref
do
    if [[ $ref =~ .*/main$ ]];
    then
        echo "Main ref received.  Deploying main branch to production..."
        git --work-tree=/var/www/html --git-dir=/srv/git/website checkout -f main
    else
        echo "Ref $ref successfully received."
	echo "Doing nothing: only the main branch may be deployed on this server."
    fi
done
